version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: graylog-mongodb
    networks:
      - graylog
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog
    restart: always

  graylog:
    image: graylog/graylog:4.3
    container_name: graylog-server
    environment:
      - GRAYLOG_PASSWORD_SECRET=admin123456789123456789
      - GRAYLOG_ROOT_PASSWORD_SHA2=e6bdfa3e93c1c93669549cc718fc8366ff422f28ac0af6696e353fee52a37fd0 # SHA256 de "admin"
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongodb:27017/graylog
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    networks:
      - graylog
    restart: always

networks:
  graylog:
    driver: bridge
